feat: 关联模型与打包配置 (#6)
* feat: update project version to 0.1.1

* feat: add role and permission management models and APIs

* feat: implement role and permission management with unique data operations

* feat: update reflect and resource configuration for enhanced class and method querying

* feat: configure logging settings and add logback configuration for file output

* feat: add NoSameId validation annotation and implement permission management enhancements

* feat: implement user management API with add, update role, and query functionalities

* feat: enhance user API with additional permissions for add, update, and query operations

* feat: update authentication endpoint and modify anonymous URL configuration

* feat: add refresh token endpoint to LoginApi for renewing authentication credentials

* feat: add Prometheus metrics support and update anonymous URL configuration

* feat: enhance build process with version reading and Docker Hub integration

diff --git a/.github/workflows/build-native.yml b/.github/workflows/build-native.yml
--- a/.github/workflows/build-native.yml
+++ b/.github/workflows/build-native.yml
@@ -1,11 +1,13 @@
 # 目前仅打包，后续再考虑上传到 docker hub
 name: Build Native Image
 on:
-#  workflow_dispatch
-   push:
-     branches: [ "main" ]
+  workflow_dispatch:
+  push:
+    branches: [ "main" ]
 permissions:
   contents: read
+env:
+  DOCKER_IMAGE_NAME: linhong4dockerhub/ksas-backend
 
 jobs:
   build:
@@ -18,7 +20,40 @@ jobs:
           distribution: 'graalvm'
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4
+      # 新增版本号读取步骤
+      - name: Read project.version
+        id: read-version
+        run: |
+          # 检查文件是否存在
+          if [ ! -f project.version ]; then
+          echo "::error::project.version file not found!"
+          exit 1
+          fi
+          
+          # 读取第一行并去除空白字符
+          VERSION=$(head -n 1 project.version | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
+          
+          # 验证版本号格式（基础校验）
+          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
+          echo "::error::Invalid version format: $VERSION"
+          exit 1
+          fi
+          
+          echo "Using version: $VERSION"
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
       - name: Make gradlew executable
         run: chmod +x ./gradlew
       - name: Build with Gradle
         run: ./gradlew bootBuildImage -x test
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Tag and Push Image
+        run: |
+          docker tag ${{ env.DOCKER_IMAGE_NAME }}:latest ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}
+          docker push ${{ env.DOCKER_IMAGE_NAME }}:latest
+          docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}         
